### PR TITLE
Moves Guardsmen Selection to Occupation Preferences

### PR DESCRIPTION
**Pull request by Kurgis**
You will no longer spawn naked and then choose a regiment, instead choose your desired place before round start in the occupations screen. This has zero balance or loadout changes, every object being given to players will remain the same, has been tested multiple times locally.

PR1

Note: The "Imperial Guardsman" in the list is Cadian.

### CODE REVIEW

**Comment by EliteRiceFarmer** [comment]
VIBE CHECK.

Wellard merge this please, we'll rework all the loadout as soon as this is in.

**Comment by EliteRiceFarmer** [comment]
> You will no longer spawn naked and then choose a regiment, instead choose your desired place before round start in the occupations screen.

REMOVE THE CADIAN VISOR FROM SERGEANT LOADOUT, I WAS SUPPOSED TO REMOVE IT, IT'S CADIAN ONLY!!!

**Comment by Kurgis** [comment]
This is ready for review.

**Comment by Kurgis** [comment]
> REMOVE THE CADIAN VISOR FROM SERGEANT LOADOUT, I WAS SUPPOSED TO REMOVE IT, IT'S CADIAN ONLY!!!

Addressed in Discord.

**Comment by Kurgis** [comment]
This is ready for review.

**Comment by EliteRiceFarmer** [comment]
> > REMOVE THE CADIAN VISOR FROM SERGEANT LOADOUT, I WAS SUPPOSED TO REMOVE IT, IT'S CADIAN ONLY!!!
> 
> Addressed in Discord.

Yes, yes we did.

**Comment by EliteRiceFarmer** [comment]
> This is ready for review.

Also create a Guide how this work so i can replicate this for Inquisition Retinue and Astarte?

**Comment by Daelso** [comment]
looks good

**Pull request merged**
