### PR TITLE
refactor and addition of uranium and phoron for the mining system

### PR DESCRIPTION
**Pull request by rtlui**
### Hello

- Did a refactor on the mining system for a more efficient one and fixed one possible runtime that was happening with the old system.
- Added Phoron and Uranium to the caves and mining system, and their refined states to the forge so it can be acquired for chemistry and such jobs

_If the phoron and uranium arent in the system for a reason please tell me and i will rapidly remove em from the PR_

### CODE REVIEW

**Comment by Daelso** [comment]
I'm mixed on this. Uranium can be used for rad trolling. it's the reason I removed it from cargo

**Comment by rtlui** [comment]
> I'm mixed on this. Uranium can be used for rad trolling. it's the reason I removed it from cargo

how lethal is uranium on IS12? like floors and such made of uranium

**Comment by Daelso** [comment]
I've never tested it but had people blowing up my DMs about radiation ruining a round

**Comment by rtlui** [comment]
just checked and radiation damage basically is around 0.050(depends on how much radiation you have on the body) per tick of toxin damage. maybe we need some testing on the server with the help of admins to measure how bad is radiation and uranium rn, to see how can we bring it to the server without it becoming a trolling tool

**Comment by reklaw9** [comment]
we already have uranium in the engineerium

**Comment by ondrej008** [comment]
> 
> 
> I've never tested it but had people blowing up my DMs about radiation ruining a round

that's some weird bay12 artifact which spams rads like 100 tilse around it, giving people fatal radiation poisoning

**Comment by rtlui** [comment]
merge when

**Comment by rtlui** [comment]
Pain
Suffering even

**Pull request merged**
