### PR TITLE
Weapon sprites fix

### PR DESCRIPTION
**Pull request by Mw1113**
Organized the weapons sprites and fixed some path issues that was making some unique weapons turn into the default energy gun. Moved all the weapons sprites into a directory under icons/obj/weapons/ which should help keep everything together. 

Added:
New weapons folders for both guns and melee
fixed path issues that caused both energy & projectile weapons to turn into default gun versions and caused invisible states and 
    variants
Language files didn't alphabetize itself before apparently so that is added in as a small extra patch for the dme.

### CODE REVIEW

**Comment by ghost** [comment]
What’s with the sudden influx of fixes this week?

**Comment by Mw1113** [comment]
I figure if I fix things here and there they wont ask me to code in squats or something. But also people are becoming more active

**Comment by ghost** [comment]
Awesome! I ain’t in the discord no more (if you’re reading this please unban me :) good to see the project is still living

**Comment by Daelso** [comment]
@Doosteroni if you can be a good boy come back

**Pull request closed without merging**
