### PR TITLE
bloodpact stuff for renegade guardsmen

### PR DESCRIPTION
**Pull request by MoitoCoitelo**
Just some basic gear for blood pact themed renegades

### CODE REVIEW

**Comment by Daelso** [comment]
please handle the conflicts

**Comment by MoitoCoitelo** [comment]
what conflicts my nigga

**Comment by MoitoCoitelo** [comment]
it shows up as verified on my end

**Comment by Kurgis** [comment]
There seems to be a lot of unrelated Baystation icons that were created in `icons/mob/onmob/uniforms.dmi` perhaps unintentionally according to icondiffs.

**Comment by MoitoCoitelo** [comment]
gonna delete it and send it again because I think I fucked up when trying to make a second PR and it all mixed poorly

**Pull request closed without merging**
