### PR TITLE
Hotkey additions/fixes

### PR DESCRIPTION
**Pull request by dr-ehle**
Two requested changes to hotkeys are implemented with this pull request.

1. 'Tab' now strictly enables hotkey mode. It no longer can be used to disable hotkey mode.
2. 'T' now strictly disables hotkey mode, focusing the interface onto the chat bar. 'T' no longer causes an input prompt to appear for the 'say' command.

### CODE REVIEW

**Comment by rtlui** [comment]
I feel that this just makes harder talking ic for people accustomed to the popup, the popup was nice and didnt require you to take your eyes off the center of the screen

**Comment by Max-023** [comment]
Yeah I agree, this isn't a good change if it is replacing say. Should either be tied to a different key or not changed at all.

**Comment by dr-ehle** [comment]
There is still a hotkey that brings up the popup for say, I believe it is F5.

**Comment by Max-023** [comment]
That's an infinitely lesser known command that would just confuse most people and just is a change I see as unnecessary.

**Comment by dr-ehle** [comment]
I would bring it up with Nobel, as he specifically requested this change. Personally, I don't believe the lack of a popup to be too disruptive. Pressing T still puts you into typing mode, which can be exited immediately by pressing tab. No popup lingers on your screen if you want to move your character before you finish typing.

**Comment by Max-023** [comment]
Of course it was nobel who requested this.

**Comment by Daelso** [comment]
Waiting for more discussion, it seems like Lifeweb/Farweb which a lot of people find very useful. I would say I'm in favor atm

**Comment by rtlui** [comment]
> I would bring it up with Nobel, as he specifically requested this change. Personally, I don't believe the lack of a popup to be too disruptive. Pressing T still puts you into typing mode, which can be exited immediately by pressing tab. No popup lingers on your screen if you want to move your character before you finish typing.


Yea you can still type, but without the popup i feel like it would disrupt the pace of the game quite a bit because people cant chat or write at the same time they look at the game screen like any other server, it can become quite problematic because then chatting and playing will be separated instead of one appearing on top of another

**Comment by dr-ehle** [comment]
Perhaps I am out of touch with player preferences (the last time I played regularly was 7 years ago), but I thought most people had always regarded the popup as a major annoyance. I definitely felt as if a box popping up and blocking view of my character was annoying at least, and game-ending in the worst circumstances if it obstructed my view of someone attacking me, for example.

I can tell that you prefer the popup, but I’m not sure that I follow your logic that having a box blocking your view of the center of the screen allows you to focus on what is happening on-screen. I would think that the popup would have the opposite effect.

**Comment by Daelso** [comment]
We're going to merge and let people try it. If people really hate it a month from now we can revert.

**Pull request merged**
